HeartView/HeartView/Controllers/ActivitatePacientiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using HealthView.BusinessLogic.ModelCore;

namespace HeartView.Controllers
{
    public class ActivitatePacientiController : Controller
    {
        // GET: ActivitatePacienti
        public ActionResult Index()
        {
            return View();
        }

        // GET: ActivitatePacienti/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ActivitatePacienti/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ActivitatePacienti/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<ActionResult> ListareActivitatePacienti(Guid pacientId)
        {
            try
            {
                var fisePacienti = await ActivitatePacientiCore.Instance().List();

                if (fisePacienti == null)
                {
                    return null;
                }

                ViewBag.IDPacient = pacientId;

                return View(fisePacienti);
            }
            catch (Exception)
            {

                throw;
            }
        }

        // GET: ActivitatePacienti/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ActivitatePacienti/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ActivitatePacienti/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ActivitatePacienti/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HeartView/HeartView/Controllers/PacientiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Threading.Tasks;
using System.Web.Mvc;
using HealthView.BusinessLogic.ModelCore;
using HealthView.Models;
using LoggingService;

namespace HeartView.Controllers
{
    public class PacientiController : Controller
    {
        // GET: Pacienti
        public ActionResult Index()
        {
            return View();
        }

        // GET: Pacienti/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }


        //public virtual async Task<ActionResult> Listare()
        //{
        //    var pacientiList = await PacientiCore.Instance().List();
        //    if (pacientiList == null)
        //    {
        //        return null;
        //    }
        //    return View(pacientiList);
        //}
        // GET: Pacienti/Create
        public ActionResult Create(Guid aspNetUserId, Guid doctorId)
        {
            ViewBag.AspNetUserId = aspNetUserId;
            ViewBag.IDDoctor = doctorId;
            return View();
        }

        // POST: Pacienti/Create
        [HttpPost]
        public async Task<ActionResult> Create(Pacienti pacientModel)
        {
            try
            {
                pacientModel.Status = "1";
                var pacient = await PacientiCore.Instance().CreateAsync(pacientModel).ConfigureAwait(false);

                return Json(pacient);
            }
            catch (Exception ex)
            {
                return Json(null);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Listare(Guid doctorId)
        {

            var pacienti = await PacientiCore.Instance().GetAllByDoctorId(doctorId).ConfigureAwait(false);

            if (pacienti != null && pacienti.Count != 0)
            {
                ViewBag.IDPacient = pacienti.FirstOrDefault().Id;
            }

            ViewBag.IDDoctor = doctorId;
          
            return View(pacienti);
        }


        [HttpGet]
        public virtual async Task<ActionResult> UpdatePacient(Guid pacientId, Guid doctorId, Guid aspNetUserId)
        {
            var model = await PacientiCore.Instance().GetAsync(pacientId).ConfigureAwait(false);


            ViewBag.IDPacient = pacientId;
            ViewBag.IDDoctor = doctorId;
            ViewBag.AspNetUserId = aspNetUserId;
            return View(model);
        }

        [HttpPost]
        public virtual async Task<ActionResult> UpdatePacient(Pacienti model)
        {
            var updatedPacient = await PacientiCore.Instance().UpdateAsync(model).ConfigureAwait(false);

            return Json(updatedPacient);
        }

        // GET: Pacienti/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Pacienti/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pacienti/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Pacienti/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HeartView/HeartView/Controllers/RecomandariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using HealthView.BusinessLogic.ModelCore;
using HealthView.Models;

namespace HeartView.Controllers
{
    public class RecomandariController : Controller
    {
        // GET: Recomandari
        public ActionResult Index()
        {
            return View();
        }

        // GET: Recomandari/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Recomandari/Create
        [HttpGet]
        public ActionResult CreateRecomandare(Guid pacientId)
        {
            ViewBag.IDPacient = pacientId;
           
            return View();
        }

        // POST: Recomandari/Create
        [HttpPost]
        public async Task<ActionResult> CreateRecomandare(Recomandari recomandareModel)
        {
            try
            {
                var recomandare = await RecomandariCore.Instance().CreateAsync(recomandareModel).ConfigureAwait(false);

                return Json(recomandare);
            }
            catch (Exception ex)
            {
                return Json(null);
            }
        }

        // GET: Recomandari/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }


        [HttpGet]
        public async Task<ActionResult> ListareRecomandariPacienti(Guid pacientId, Guid doctorId)
        {
            try
            {
                var recomandariPacient = await RecomandariCore.Instance().List();


                ViewBag.IDPacient = pacientId;
                ViewBag.IDDoctor = doctorId;

                return View(recomandariPacient);
            }
            catch (Exception)
            {

                throw;
            }
        }


        [HttpGet]
        public virtual async Task<ActionResult> UpdateRecomandare(Guid idRecomandare, Guid pacientId, Guid doctorId)
        {
            var model = await RecomandariCore.Instance().GetAsync(pacientId).ConfigureAwait(false);


            ViewBag.IDRecomandare = idRecomandare;
            ViewBag.IDPacient = pacientId;
            ViewBag.IDDoctor = doctorId;
            return View(model);
        }

        [HttpPost]
        public virtual async Task<ActionResult> UpdateRecomandare(Recomandari model)
        {
            var updatedRecomandare = await RecomandariCore.Instance().UpdateAsync(model).ConfigureAwait(false);

            return Json(updatedRecomandare);
        }

        // POST: Recomandari/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Recomandari/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Recomandari/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HeartView/HeartView/Views/Pacienti/Create.cshtml
@model HealthView.Models.Pacienti

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Create</title>
</head>
<body>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")


@using (Html.BeginForm(null, null, FormMethod.Post, new {id = "save-pacient"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pacienti</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.NumePacient, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumePacient, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.NumePacient, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrenumePacient, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrenumePacient, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.PrenumePacient, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CNP, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.CNP, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.CNP, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Varsta, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Varsta, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Varsta, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Adresa, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Telefon, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Telefon, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Ocupatie, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ocupatie, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Ocupatie, "", new {@class = "text-danger"})
            </div>
        </div>
       


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Create" class="btn btn-default" onclick="pacientModule.create('@ViewBag.AspNetUserId','@ViewBag.IDDoctor');"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
</body>
</html>

@section Scripts{
    @Scripts.Render("~/bundles/pacientScript")
    @Scripts.Render("~/bundles/commonScript")
}

HeartView/HeartView/Views/Pacienti/Listare.cshtml
@model IEnumerable<HealthView.Models.Pacienti>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Pacienti</title>
    <link rel="stylesheet" href="~/Content/Custom/pacientistyle.css">
</head>

<body>
    <div class="heart">&#x2665;</div>
    <div class="table-title">
        <h2>Pacienti</h2>
    </div>

    <input type="button" class="btn btn-default" style="background-color: #31A3D3" value="Inregistrare pacient" onclick="location.href = '@Url.Action("Register", "Account", new {doctorId = ViewBag.IDDoctor})'" />
    <
    @*<a onclick="location.href='@Url.Action("Register","Account")'" class="myButton"> Inregistrare pacienti</a>*@

    <table class="table-fill">
        <thead>
            <tr>
                <th class="text-left">
                    @Html.DisplayNameFor(model => model.NumePacient)
                </th>
                <th class="text-left">
                    @Html.DisplayNameFor(model => model.PrenumePacient)
                </th>
                <th class="text-left">
                    @Html.DisplayNameFor(model => model.CNP)
                </th>
                <th class="text-left">
                    @Html.DisplayNameFor(model => model.Varsta)
                </th>
                <th class="text-left">
                    @Html.DisplayNameFor(model => model.Adresa)
                </th>
                <th class="text-left">
                    @Html.DisplayNameFor(model => model.Telefon)
                </th>
                <th class="text-left">
                    @Html.DisplayNameFor(model => model.Ocupatie)
                </th>
                <th class="text-left">
                    Actiuni
                </th>

            </tr>
        </thead>
        <tbody class="table-hover"></tbody>

        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumePacient)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrenumePacient)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CNP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Varsta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adresa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefon)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ocupatie)
                </td>

                <td>
                    @Html.ActionLink("Edit", "UpdatePacient", "Pacienti", new { pacientId = item.Id , doctorId = item.IDDoctor, aspNetUserId = item.AspNetUserId}, null)|
                    @Html.ActionLink("Details", "ListareActivitatePacienti", "ActivitatePacienti", new { pacientId = item.Id }, null) |
                    @Html.ActionLink("Listare Recomandari", "ListareRecomandariPacienti", "Recomandari", new { pacientId = item.Id, doctorId = item.IDDoctor, aspNetUserId = item.AspNetUserId }, null) |
                    @Html.ActionLink("Creare Recomandare", "CreateRecomandare", "Recomandari", new { pacientId = item.Id }, null) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, null)

                </td>
            </tr>
        }

    </table>
</body>
</html>

HeartView/HeartView/Views/Pacienti/UpdatePacient.cshtml
@model HealthView.Models.Pacienti

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Create</title>
</head>
<body>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")


@using (Html.BeginForm(null, null, FormMethod.Post, new {id = "save-pacient"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.NumePacient, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumePacient, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.NumePacient, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrenumePacient, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrenumePacient, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.PrenumePacient, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CNP, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.CNP, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.CNP, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Varsta, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Varsta, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Varsta, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Adresa, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Telefon, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Telefon, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Ocupatie, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ocupatie, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Ocupatie, "", new {@class = "text-danger"})
            </div>
        </div>
       


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Save" class="btn btn-default" onclick="pacientModule.updatePacient('@ViewBag.IDPacient','@ViewBag.IDDoctor', '@ViewBag.AspNetUserId');"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
</body>
</html>

@section Scripts{
    @Scripts.Render("~/bundles/pacientScript")
    @Scripts.Render("~/bundles/commonScript")
}